# Generated by Django 6.1a1 on 2026-06-23 19:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='name')),
                ('short_name', models.CharField(max_length=50, unique=True, verbose_name='short name')),
                ('domain', models.CharField(help_text='e.g. alu.edu.rw', max_length=255, unique=True, verbose_name='domain')),
                ('logo_url', models.URLField(blank=True, verbose_name='logo URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
            ],
            options={
                'verbose_name_plural': 'Universities',
                'ordering': ['name'],
            },
        ),
    ]
