# Generated by Django 6.1a1 on 2026-06-25 18:34

from django.db import migrations


def create_moderator_group(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Group.objects.get_or_create(name="UniversityModerator")

def remove_moderator_group(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Group.objects.filter(name="UniversityModerator").delete()

class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0002_university_moderators'),
    ]

    operations = [
        migrations.RunPython(create_moderator_group, remove_moderator_group)
    ]
