# Generated by Django 6.1a1 on 2026-06-23 22:28

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


from django.contrib.postgres.operations import TrigramExtension, BtreeGinExtension

class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ('universities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        TrigramExtension(),
        BtreeGinExtension(),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='slug')),
                ('description', models.TextField(verbose_name='description')),
                ('start_time', models.DateTimeField(verbose_name='start time')),
                ('end_time', models.DateTimeField(verbose_name='end time')),
                ('location', models.CharField(max_length=255, verbose_name='location')),
                ('is_virtual', models.BooleanField(default=False, verbose_name='is virtual')),
                ('virtual_link', models.URLField(blank=True, verbose_name='virtual link')),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='events/banners/', verbose_name='banner image')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20, verbose_name='status')),
                ('capacity', models.PositiveIntegerField(default=0, help_text='0 means unlimited', verbose_name='capacity')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='price')),
                ('payment_link', models.URLField(blank=True, verbose_name='payment link')),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='events.category', verbose_name='category')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organized_events', to=settings.AUTH_USER_MODEL, verbose_name='organizer')),
                ('universities', models.ManyToManyField(related_name='events', to='universities.university', verbose_name='universities')),
            ],
            options={
                'ordering': ['-start_time'],
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='events_even_search__5f308c_gin')],
            },
        ),
    ]
