# Generated by Django 6.1a1 on 2026-06-25 12:05

import django.contrib.postgres.indexes
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event'),
        ('universities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='event',
            index=django.contrib.postgres.indexes.GinIndex(fields=['title'], name='event_title_trgm_idx', opclasses=['gin_trgm_ops']),
        ),
        migrations.RunSQL(
            sql='''
            CREATE TRIGGER event_search_vector_update
            BEFORE INSERT OR UPDATE ON events_event
            FOR EACH ROW EXECUTE PROCEDURE tsvector_update_trigger(
                search_vector, 'pg_catalog.english', title, description, location
            );
            UPDATE events_event SET search_vector = NULL;
            ''',
            reverse_sql='''
            DROP TRIGGER IF EXISTS event_search_vector_update ON events_event;
            '''
        )
    ]
