# Generated by Django 6.1a1 on 2026-06-25 19:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0005_rsvp_savedevent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FlagReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('reason', models.TextField(verbose_name='reason')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RESOLVED', 'Resolved'), ('DISMISSED', 'Dismissed')], default='PENDING', max_length=20, verbose_name='status')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flag_reports', to='events.event')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flag_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ModerationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('action', models.CharField(choices=[('APPROVED', 'Approved Event'), ('REJECTED', 'Rejected Event'), ('FLAG_RESOLVED', 'Resolved Flag'), ('FLAG_DISMISSED', 'Dismissed Flag')], max_length=20, verbose_name='action')),
                ('reason', models.TextField(blank=True, verbose_name='reason')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderation_logs', to='events.event')),
                ('moderator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
