# Generated by Django 6.1a1 on 2026-06-25 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moderationlog',
            name='action',
            field=models.CharField(choices=[('APPROVED', 'Approved Event'), ('REJECTED', 'Rejected Event'), ('FLAGGED', 'Flagged Event'), ('FLAG_RESOLVED', 'Resolved Flag'), ('FLAG_DISMISSED', 'Dismissed Flag')], max_length=20, verbose_name='action'),
        ),
    ]
