# Generated by Django 6.1a1 on 2026-06-25 12:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizerProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('bio', models.TextField(blank=True, verbose_name='bio')),
                ('website', models.URLField(blank=True, verbose_name='website')),
                ('social_links', models.JSONField(blank=True, default=dict, verbose_name='social links')),
                ('trust_tier', models.IntegerField(choices=[(1, 'New Organizer'), (2, 'Trusted Organizer'), (3, 'Verified Partner')], default=1, verbose_name='trust tier')),
                ('is_verified', models.BooleanField(default=False, verbose_name='is verified')),
                ('successful_events_count', models.PositiveIntegerField(default=0, help_text='Number of approved events without flags. Reaching 3 unlocks TRUSTED tier.', verbose_name='successful events count')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='organizer_profile', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Organizer Profile',
                'verbose_name_plural': 'Organizer Profiles',
            },
        ),
    ]
